'use client';
import { notFound } from 'next/navigation';
import Link from 'next/link';
import { ArrowLeft, ArrowRight, ArrowUpRight, Check, Layers3, MousePointer2, Sparkles } from 'lucide-react';
import { motion, useScroll, useTransform } from 'framer-motion';
import { useRef } from 'react';
import { projects } from '../../work-data';
import SiteNav from '../../components/SiteNav';

function ProductVisual({type}:{type:string}){
 const common=<><div className="pv-top"><span>●</span><span>●</span><span>●</span><b>PRODUCT / EXPERIENCE</b></div></>;
 if(type==='finance'||type==='memo') return <div className="product-visual finance-visual">{common}<div className="pv-dashboard"><aside><strong>TF</strong><i/><i/><i/><i/></aside><main><div className="pv-title"><span>Good morning</span><b>Overview ↗</b></div><div className="kpi-row"><div><small>AVAILABLE</small><strong>$24,860</strong><em>+12.8%</em></div><div><small>IN FLOW</small><strong>$8,420</strong><em>+4.2%</em></div><div><small>OUTFLOW</small><strong>$3,184</strong><em>-2.1%</em></div></div><div className="chart-card"><div className="chart-head"><span>Cash flow</span><small>6 months</small></div><svg viewBox="0 0 600 180"><path d="M0 145 C60 135 80 115 130 120 S190 70 250 100 330 30 390 70 450 55 510 65 555 28 600 40" fill="none" stroke="currentColor" strokeWidth="4"/><path d="M0 145 C60 135 80 115 130 120 S190 70 250 100 330 30 390 70 450 55 510 65 555 28 600 40 V180 H0Z" fill="currentColor" opacity=".08"/></svg></div><div className="mini-row"><div/><div/><div/></div></main></div></div>;
 if(type==='chat') return <div className="product-visual chat-visual">{common}<div className="chat-shell"><aside><strong>OQ</strong><span>New chat</span><span>Arabic / English</span><span>Saved</span></aside><main><div className="chat-head">Oqaabi <i>● online</i></div><div className="bubble user">Help me plan my week.</div><div className="bubble ai"><b>Here’s a simple starting point.</b><br/><span>3 priorities · 2 meetings · 1 focused block</span><div className="chips"><i>Make a plan</i><i>Translate</i><i>Explain</i></div></div><div className="chat-input">Ask anything <span>↗</span></div></main></div></div>;
 if(type==='car') return <div className="product-visual car-visual">{common}<div className="car-ui"><div className="car-nav"><span>09:41</span><b>HOME</b><span>24°</span></div><div className="car-map"><div className="road r1"/><div className="road r2"/><div className="route">↗</div><div className="map-card"><small>ARRIVE 10:12</small><strong>18 min</strong><span>12.4 km · Main Boulevard</span></div></div><div className="car-controls"><div>♫<span>Media</span></div><div>⌖<span>Navigation</span></div><div>☼<span>Climate</span></div><div>◉<span>Vehicle</span></div></div></div></div>;
 if(type==='learn') return <div className="product-visual learn-visual">{common}<div className="learn-ui"><aside><strong>e</strong><span>Learn</span><span>Practice</span><span>Progress</span></aside><main><div className="learn-hero"><small>YOUR NEXT STEP</small><h3>Every day, a little<br/><i>more fluent.</i></h3><div className="progress"><span style={{width:'68%'}}/></div><b>68% weekly goal</b></div><div className="lesson-row"><div><small>CONTINUE</small><strong>Everyday conversations</strong><span>12 min · 4 exercises</span></div><button>Start →</button></div><div className="lesson-grid"><div/><div/><div/></div></main></div></div>;
 if(type==='ai') return <div className="product-visual ai-visual">{common}<div className="ai-ui"><aside><strong>F2</strong><span>Workspace</span><span>Automation</span><span>Review queue</span></aside><main><div className="ai-head"><div><small>RECOMMENDATION</small><h3>Resolve duplicate vendor records</h3></div><button>Approve</button></div><div className="ai-grid"><div className="evidence"><small>EVIDENCE</small><b>4 matching signals</b><span>Company · address · invoice · domain</span><div className="signal"><i/><i/><i/><i/></div></div><div className="decision"><small>NEXT ACTION</small><strong>Merge records</strong><span>2 records will be archived</span><button>Review changes ↗</button></div></div></main></div></div>;
 return <div className="product-visual default-visual">{common}<div className="generic-ui"><div/><div/><div/><div/><div/><div/></div></div>;
}


function MockupGallery({type}:{type:string}){
 const sets:any={
  ai:[['COMMAND CENTER','Queue / 24 active','Review priority','High confidence'],['EVIDENCE LAYER','Signal strength','4 matching signals','Source trace ↗'],['APPROVAL FLOW','Before → After','Human review','Confirm action']],
  chat:[['LANGUAGE MODE','English','العربية','Auto detect'],['CONVERSATION','Summarize this','Translate','Explain simply'],['RESPONSE','Answer','Sources','Next actions']],
  finance:[['MONEY OVERVIEW','Available balance','$24,860','+12.8%'],['PAYMENT FLOW','Recipient','Amount','Confirm'],['ACTIVITY','Groceries','Transfer','Subscription']],
  car:[['DRIVE MODE','Navigation','18 min','12.4 km'],['MEDIA','Now playing','Night Drive','09:41'],['CONTEXT','Weather 24°','Next turn','Vehicle status']],
  learn:[['LEARNING HOME','68% weekly goal','4 day streak','Next lesson'],['LESSON','Vocabulary','Practice','Feedback'],['PROGRESS','Words learned','Accuracy','Weekly trend']],
  memo:[['FINANCIAL OVERVIEW','Revenue','$82.4K','+18.4%'],['CASH FLOW','Income','Expenses','Net flow'],['TRANSACTIONS','Invoice #1042','Transfer','Subscription']]
 };
 const data=sets[type]||sets.memo;
 return <section className="mockup-gallery">
   <div className="gallery-intro"><div><span className="label">INTERFACE STUDY</span><h2>Designed as a <i>system.</i></h2></div><p>Supporting interface moments turn the hero screen into a product story: hierarchy, states and interaction patterns are shown as connected parts of one experience.</p></div>
   <div className="gallery-grid">
    {data.map((card:any[],i:number)=><motion.article className={'mock-card mock-'+type+'-'+i} key={card[0]} initial={{opacity:0,y:35}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:.2}} transition={{duration:.6,delay:i*.08}}>
      <div className="mock-card-chrome"><span>{String(i+1).padStart(2,'0')}</span><b>{card[0]}</b><span>↗</span></div>
      <div className="mock-screen">
        <div className="screen-title"><small>{card[1]}</small><strong>{card[2]}</strong></div>
        <div className="screen-main"><div className="screen-orb"/><div className="screen-value">{card[3]}</div></div>
        <div className="screen-lines"><i/><i/><i/></div>
        <div className="screen-actions"><span>{card[1]}</span><button>{type==='chat'?'Ask':type==='car'?'Drive':type==='learn'?'Continue':type==='ai'?'Review':'Open'} ↗</button></div>
      </div>
    </motion.article>)}
   </div>
 </section>
}

export default function CaseStudyClient({slug}:{slug:string}){
 const p=projects.find(x=>x.slug===slug); if(!p) notFound();
 const idx=projects.findIndex(x=>x.slug===p.slug); const next=projects[(idx+1)%projects.length]; const hero=useRef(null); const {scrollYProgress}=useScroll({target:hero,offset:['start start','end start']}); const y=useTransform(scrollYProgress,[0,1],[0,120]);
 return <main className="case-page">
  <SiteNav caseStudy />
  <section ref={hero} className="case-hero"><Link className="back" href="/#work"><ArrowLeft size={15}/> Back to selected work</Link><motion.div className="case-orbit" style={{y}}><span>{p.number}</span><span>{p.accent}</span></motion.div><span className="label">{p.kicker}</span><h1>{p.title}</h1><p className="case-summary">{p.summary}</p><div className="case-meta"><div><span>ROLE</span><strong>{p.role}</strong></div><div><span>SCOPE</span><strong>{p.scope.join(' · ')}</strong></div><div><span>CASE STUDY</span><strong>Product design process · selected work</strong></div></div></section>
  <section className="case-hero-art"><ProductVisual type={p.visual}/><div className="art-caption"><span>01</span><span>Hero interface reconstruction / presentation visual</span><span>Scroll to explore ↓</span></div></section>
  <MockupGallery type={p.visual}/><section className="case-intro"><div><span className="label">THE CONTEXT</span><h2>Start with the <i>why.</i></h2></div><p>{p.context}</p></section>
  <section className="discovery-section"><div className="section-head"><div><span className="label">01 / DISCOVERY</span><h2>What the <i>experience revealed.</i></h2></div><p>Before shaping the interface, the work is framed around the user's mental model, moments of friction and the opportunities that can change the journey.</p></div><div className="insight-columns"><div><span className="label">KEY OBSERVATIONS</span>{p.discovery.map((x,i)=><motion.div className="insight-item" key={x} initial={{opacity:0,x:-18}} whileInView={{opacity:1,x:0}} viewport={{once:true}} transition={{delay:i*.06}}><span>0{i+1}</span><p>{x}</p></motion.div>)}</div><div><span className="label">PAIN POINTS</span>{p.painPoints.map((x,i)=><div className="pain-item" key={x}><span>×</span><p>{x}</p></div>)}<span className="label opportunity-label">OPPORTUNITIES</span>{p.opportunities.map((x,i)=><div className="opportunity-item" key={x}><span>↗</span><p>{x}</p></div>)}</div></div></section><section className="ia-section"><div><span className="label">02 / INFORMATION ARCHITECTURE</span><h2>Structure before <i>surface.</i></h2><p>The interface follows a clear information hierarchy so visual polish supports the product model rather than hiding it.</p></div><div className="ia-map">{p.ia.map((x,i)=><motion.div key={x} initial={{opacity:0,y:18}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{delay:i*.05}}><span>0{i+1}</span><strong>{x}</strong>{i<p.ia.length-1&&<b>→</b>}</motion.div>)}</div></section><section className="case-problem"><div className="problem-card"><span className="label">THE PROBLEM</span><h2>{p.problem}</h2></div><div className="hypothesis"><span className="label">DESIGN HYPOTHESIS</span><p>{p.hypothesis}</p><div className="audience"><span>WHO IT SERVES</span><strong>{p.audience}</strong></div></div></section>
  <section className="journey"><div className="section-head"><div><span className="label">03 / USER JOURNEY</span><h2>From first intent<br/><i>to useful outcome.</i></h2></div><p>The journey is intentionally expressed as a sequence of decisions, not a list of screens. This keeps the case study about behavior and product thinking.</p></div><div className="journey-track">{p.journey.map((step,i)=><motion.div key={step} initial={{opacity:0,y:20}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:.3}} transition={{delay:i*.08}}><span>0{i+1}</span><b>{step}</b><i>{i===0?'entry':i===p.journey.length-1?'outcome':'decision'}</i></motion.div>)}</div></section>
  <section className="process"><div className="process-head"><span className="label">04 / PROCESS</span><h2>How the work <i>moved forward.</i></h2></div><div className="stage-grid">{p.stages.map((s,i)=><motion.article key={s.title} initial={{opacity:0,y:30}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:.18}} transition={{delay:i*.05}}><div className="stage-num">{String(i+1).padStart(2,'0')}</div><h3>{s.title}</h3><p>{s.body}</p><div className="outputs">{s.outputs.map(o=><span key={o}><Check size={12}/>{o}</span>)}</div></motion.article>)}</div></section>
  <section className="decision-showcase"><div className="decision-copy"><span className="label">05 / DESIGN DECISIONS</span><h2>Small choices create the <i>experience.</i></h2><p>These are the decisions that make the final interface feel coherent rather than merely polished.</p></div><div className="decision-list">{p.decisions.map((d,i)=><div key={d}><span>0{i+1}</span><p>{d}</p></div>)}</div></section>
  <section className="system-section"><div><span className="label">06 / UI SYSTEM</span><h2>A visual language that <i>scales.</i></h2><p>Instead of designing each screen independently, repeated behavior becomes a system. That gives future screens the same rhythm and makes implementation more predictable.</p></div><div className="system-board"><div className="system-top"><span>COMPONENTS</span><Layers3 size={16}/></div>{p.system.map((s,i)=><div className="system-row" key={s}><span>0{i+1}</span><strong>{s}</strong><b>↗</b></div>)}</div></section>
  <section className="outcome-section"><div className="outcome-visual"><div className="outcome-grid"/><div className="floating-card"><MousePointer2 size={15}/><span>Designed around the decision.</span></div><div className="floating-orbit"><Sparkles/></div></div><div className="outcome-copy"><span className="label">07 / OUTCOME</span><h2>{p.outcome}</h2><p>{p.note}</p></div></section>
  <section className="case-next"><Link href="/#work"><span>All work</span><ArrowUpRight/></Link><Link href={'/work/'+next.slug}><small>NEXT CASE STUDY</small><span>{next.title}</span><ArrowRight/></Link></section>
  <footer><span>© 2026 Tayyaba Fakhar</span><span>Designed with intent. Built for humans.</span><Link href="/#top">Back to top ↑</Link></footer>
 </main>
}
