'use client';
import { motion, useScroll, useTransform } from 'framer-motion';
import { ArrowUpRight, Download, MoveUpRight, Sparkles } from 'lucide-react';
import { useRef } from 'react';
import { projects } from './work-data';
import SiteNav from './components/SiteNav';


function ProjectThumbnail({project,index}:{project:any,index:number}){
 const v=project.visual;
 return <div className={`project-art project-art-${v} art-${index+1}`}>
   <div className="project-art-top"><span>{project.number}</span><span>{project.accent}</span></div>
   <div className="thumb-noise"/>
   {v==='ai' && <div className="thumb-ui ai-ui"><div className="ui-sidebar"><b>F2</b><i/><i/><i/><i/></div><div className="ui-main"><div className="ui-head"><span>Workspace</span><strong>AI Copilot</strong></div><div className="ai-command"><span>Ask F2 to analyze this workflow</span><b>⌁</b></div><div className="ai-grid"><div className="ai-card ai-card-large"><small>RECOMMENDATION</small><strong>Reduce approval steps</strong><em>+ 18% estimated efficiency</em><div className="mini-bars"><i/><i/><i/><i/></div></div><div className="ai-card"><small>EVIDENCE</small><strong>7 signals</strong><span className="mini-ring">72%</span></div></div></div></div>}
   {v==='chat' && <div className="thumb-ui chat-ui"><div className="chat-top"><span>OQAABI</span><b>AI assistant</b></div><div className="chat-body"><div className="bubble bubble-user">Show me the shortest route.</div><div className="bubble bubble-ai">Here’s the clearest option. I can also compare alternatives.</div><div className="chat-actions"><span>Compare</span><span>Open route</span></div><div className="chat-input">Ask anything <b>↑</b></div></div></div>}
   {v==='finance' && <div className="thumb-ui finance-ui"><div className="finance-head"><span>Good morning</span><b>•••</b></div><div className="balance-card"><small>Total balance</small><strong>$24,860<span>.42</span></strong><em>+12.8% this month</em><div className="sparkline"><i/><i/><i/><i/><i/><i/><i/></div></div><div className="finance-row"><span>Recent activity</span><b>View all</b></div><div className="txn"><i>↗</i><span>Acme Studio<small>Today · Design services</small></span><strong>+$2,400</strong></div><div className="txn"><i>−</i><span>Cloud hosting<small>Yesterday</small></span><strong>−$280</strong></div></div>}
   {v==='car' && <div className="thumb-ui car-ui"><div className="car-top"><span>09:41</span><b>CARLUEX</b><span>74%</span></div><div className="car-map"><div className="route-line"/><div className="map-card"><small>ARRIVE IN</small><strong>18 min</strong><span>12.4 km · Via Blue Area</span></div></div><div className="car-controls"><span>◀</span><b>Now Playing</b><span>▶</span></div></div>}
   {v==='learn' && <div className="thumb-ui learn-ui"><div className="learn-top"><span>Good evening, Sara</span><b>72%</b></div><div className="lesson-card"><small>CONTINUE LEARNING</small><strong>Everyday conversations</strong><div className="lesson-progress"><i/></div><span>Lesson 08 · 12 min</span><button>Continue →</button></div><div className="lesson-row"><span>Weekly progress</span><strong>4 / 5 days</strong></div></div>}
   {v==='memo' && <div className="thumb-ui memo-ui"><div className="memo-head"><span>Overview</span><b>September 2026</b></div><div className="memo-chart"><div className="chart-label"><small>Cash flow</small><strong>$18.4k</strong></div><svg viewBox="0 0 420 130" preserveAspectRatio="none"><path d="M0 98 C45 75 60 90 105 70 S165 76 205 52 260 66 300 38 355 48 420 20"/><path d="M0 110 C55 105 75 106 115 96 S170 104 215 88 260 92 300 74 350 80 420 62"/></svg></div><div className="memo-stats"><div><small>Income</small><b>+12.4%</b></div><div><small>Spend</small><b>−4.8%</b></div><div><small>Saved</small><b>18.2%</b></div></div></div>}
   <div className="thumb-glow"/><div className="thumb-caption"><span>View case study</span><ArrowUpRight size={16}/></div>
 </div>
}

function Sketch({className=''}){return <svg className={className} viewBox="0 0 600 280" fill="none" aria-hidden="true"><path d="M10 230 C80 90 125 245 200 125 S320 70 370 180 475 230 590 55" stroke="currentColor" strokeWidth="1.5" strokeDasharray="6 8"/><circle cx="200" cy="125" r="5" fill="currentColor"/><circle cx="370" cy="180" r="5" fill="currentColor"/><path d="M95 40h140M95 55h90M410 55h95M410 70h62" stroke="currentColor" opacity=".35"/></svg>}

export default function Home(){
 const hero=useRef(null); const {scrollYProgress}=useScroll({target:hero,offset:['start start','end start']}); const y=useTransform(scrollYProgress,[0,1],[0,180]);
 return <main>
  <SiteNav />
  <section id="top" ref={hero} className="hero"><div className="hero-grid"/><motion.div className="hero-sketch" style={{y}}><Sketch/></motion.div><div className="eyebrow"><span className="dot"/> AVAILABLE FOR SELECTED OPPORTUNITIES · REMOTE / RELOCATION</div><h1>Designing <em>clarity</em><br/>for complex products.</h1><p className="hero-copy">I’m Tayyaba Fakhar — a Lead Product & UI/UX Designer turning ambitious ideas, AI capabilities and complex workflows into intuitive digital experiences.</p><div className="hero-actions"><a className="button dark" href="#work">Explore selected work <MoveUpRight size={17}/></a><a className="button light" href="/Tayyaba-Fakhar-CV.pdf">Download CV <Download size={16}/></a></div><div className="hero-meta"><span>6+ years</span><span>AI · SaaS · Fintech · EdTech</span><span>Islamabad · Remote-ready</span></div></section>
  <section className="statement"><p>Good design doesn’t hide complexity.<br/><strong>It gives complexity a shape people can understand.</strong></p></section>
  <section id="work" className="work section"><div className="section-head"><div><span className="label">01 / SELECTED WORK</span><h2>Work that moves<br/><i>from problem to product.</i></h2></div><p>I combine discovery, UX thinking, systems, high-fidelity UI and design QA — with a strong visual layer that makes products feel intentional.</p></div><div className="project-grid">{projects.map((p,i)=><motion.a initial={{opacity:0,y:30}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:.15}} transition={{delay:i*.05}} href={'/work/'+p.slug} className="project" key={p.slug}><ProjectThumbnail project={p} index={i}/><div className="project-info"><div><span className="kicker">{p.kicker}</span><h3>{p.title}</h3><p>{p.summary}</p></div><ArrowUpRight className="arrow"/></div><div className="tags">{p.scope.slice(0,3).map(t=><span key={t}>{t}</span>)}</div></motion.a>)}</div></section>
  <section id="about" className="about section"><div className="about-stamp">TAYYABA<br/>FAKHAR<br/><span>PRODUCT DESIGN</span></div><div><span className="label">02 / ABOUT</span><h2>Design is my way of<br/><i>making sense of things.</i></h2><p>I’ve spent 6+ years moving between product design, visual communication and delivery — from AI and cloud-modernisation initiatives to fintech, EdTech, e-commerce, mobile utilities and public-sector-facing experiences.</p><p>Today, I work where product thinking meets visual craft: shaping flows, systems, interfaces and stories that teams can actually build.</p><div className="metrics"><div><b>6+</b><span>years designing</span></div><div><b>50+</b><span>interfaces & assets</span></div><div><b>5</b><span>design disciplines</span></div></div></div></section>
  <section id="capabilities" className="capabilities section"><span className="label">03 / CAPABILITIES</span><div className="cap-grid"><div><b>01</b><h3>Product & UX</h3><p>Discovery · research · journey mapping · IA · flows · wireframes · prototyping · usability testing</p></div><div><b>02</b><h3>UI & Systems</h3><p>High-fidelity UI · responsive design · design systems · components · tokens · visual design</p></div><div><b>03</b><h3>AI-enabled Design</h3><p>AI-assisted workflows across ChatGPT, Claude, Perplexity, Uizard, Lovable, v0, Cursor, Bolt and Midjourney.</p></div><div><b>04</b><h3>Delivery & QA</h3><p>Accessibility principles · developer handoff · implementation review · stakeholder alignment · Agile/Scrum</p></div></div></section>
  <section className="experience section"><span className="label">04 / EXPERIENCE</span><div className="timeline"><div><span>2025 — NOW</span><h3>ConfidencEway</h3><p>Lead Graphics & UI/UX Designer · AI · cloud modernisation · automation · digital transformation</p></div><div><span>2023 — 2025</span><h3>Canz Technologies</h3><p>Lead UI/UX Designer · web/mobile · design systems · AI-enabled products</p></div><div><span>2022 — 2023</span><h3>ThinkMENA LLC</h3><p>Product Manager & Creative Lead · fintech · gaming · startup transformation</p></div><div><span>2022</span><h3>Extendztech LLC</h3><p>Senior UI/UX Designer · SaaS dashboards · visual systems · developer-ready UI</p></div></div></section>
  <section id="contact" className="contact"><div className="contact-orbit"><Sparkles/></div><span className="label">05 / LET’S MAKE SOMETHING GREAT</span><h2>Have a hard product<br/><i>problem to untangle?</i></h2><p>Let’s turn it into something people actually enjoy using.</p><a className="contact-email" href="mailto:tayyabafakhar.biz@gmail.com">tayyabafakhar.biz@gmail.com <ArrowUpRight/></a><div className="contact-actions"><a className="contact-pill" href="mailto:tayyabafakhar.biz@gmail.com">Email me <ArrowUpRight size={15}/></a><a className="contact-pill" href="https://www.linkedin.com/in/tayyaba-fakhar" target="_blank" rel="noreferrer">LinkedIn <ArrowUpRight size={15}/></a><a className="contact-pill" href="https://www.behance.net/Tayyabafakhar" target="_blank" rel="noreferrer">Behance <ArrowUpRight size={15}/></a></div></section>
  <footer><span>© 2026 Tayyaba Fakhar</span><span>Designed with intent. Built for humans.</span><a href="#top">Back to top ↑</a></footer>
 </main>
}
